# Generated by Django 4.2.8 on 2023-12-20 23:08

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_postattachment'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('objManager', django.db.models.manager.Manager()),
            ],
        ),
    ]
